# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-11 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_article_hastag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='hastag',
            new_name='hashtag',
        ),
    ]
