# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-12 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20171112_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Heading',
        ),
        migrations.DeleteModel(
            name='Subeading',
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
