# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20171112_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(choices=[('ap', 'approved'), ('na', 'not approved')], default='na', max_length=2),
        ),
    ]
