# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-12 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20171112_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commenting',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
    ]
