# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-12 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20171112_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved_comment',
            field=models.CharField(choices=[('ap', 'approved'), ('na', 'not approved')], default='na', max_length=2),
        ),
    ]
